version: '3.3'

services:
  gopher:
    image: prodhe/gopher:latest
    ports:
      - 70:70
    command: server
    networks:
      - traefik_traefik
    volumes:
      - /opt/gopher/public:/public
    environment:
      - GOPHER_ADDRESS=gopher.project.lambla.eu
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gopher.rule=Host(`gopher.project.lambla.eu`)"
        - "traefik.http.routers.gopher.entrypoints=web"
        - "traefik.http.services.gopher.loadbalancer.server.port=70"
        
networks:
  traefik_traefik:
    driver: overlay
    external: true
