version: '3.3'

services:
  gopher:
    image: prodhe/gopher:latest
    ports:
      - 70:70
    networks:
      - traefik_traefik
    volumes:
      - /opt/gopher/public:/public
    environment:
      - GOPHER_ADDRESS=gopher.project.lambla.eu
      - PUID=1001
      - PGID=1002
    deploy:
      restart_policy:
        condition: none
        
networks:
  traefik_traefik:
    driver: overlay
    external: true
